"""ReportEngine prompts."""

from .report_agent import (
    REPORT_AGENT_SYSTEM_PROMPT,
    REPORT_AGENT_HTML_PROMPT,
    REPORT_AGENT_MODIFIABLE_PROMPT,
)

__all__ = [
    "REPORT_AGENT_SYSTEM_PROMPT",
    "REPORT_AGENT_HTML_PROMPT",
    "REPORT_AGENT_MODIFIABLE_PROMPT",
]
