"""AnalysisAgent prompts."""

from .analysis_agent import (
    ANALYSIS_AGENT_SYSTEM_PROMPT,
    ANALYSIS_AGENT_SPOT_ANALYSIS_PROMPT,
    ANALYSIS_AGENT_ITINERARY_PROMPT,
)

__all__ = [
    "ANALYSIS_AGENT_SYSTEM_PROMPT",
    "ANALYSIS_AGENT_SPOT_ANALYSIS_PROMPT",
    "ANALYSIS_AGENT_ITINERARY_PROMPT",
]
